version: "3.9"
services:
  controller:
    build: .
    #    ports:
    #      - "8000:5000"
    environment:
      PORT: 80
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123
  s3:
    image: "minio/minio:latest"
    command:
      - server
      - /data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root_password
  speech_recognizer:
    build: ./../speech-recognizer

